In [1]:
import pandas as pd 
import numpy as np

In [2]:
# SERIES 

labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array ([10, 20, 30])
d = {1:10 , 2:20, 3:30}


pd.Series(my_list, index= labels)

a    10
b    20
c    30
dtype: int64

In [3]:
# DATA FRAMES (by dict)

data = {
    'Names' : ["Harsh", "sukhi", "anushka", "niharika", "pratham", "ambika", "shambhavi"],
    'age' :[19, 20, 20, 21, 20, 21, 19],
    'city' : ["bhopal" , "ashok nagar", "narela", "vidisha", "chindwara", "arera", "kolar"],
    'salary' :[65000, 68000, 70000, 65000, 68000, 75000, 71000]
}

df1 = pd.DataFrame(data)
df1

       Names  age         city  salary
0      Harsh   19       bhopal   65000
1      sukhi   20  ashok nagar   68000
2    anushka   20       narela   70000
3   niharika   21      vidisha   65000
4    pratham   20    chindwara   68000
5     ambika   21        arera   75000
6  shambhavi   19        kolar   71000

In [4]:
# DATA FRAME (by list)

data2 = [
    ["Harsh" , 19 , "bhoopal", 65000],
    ["sukhi" , 20, "ashok nagar" , 68000],
    ["pratham " , 20, "chindwara", 64000],
    ["nishant" , 24, "sagar" , 66000],
    ["ravi" , 25, "bhopal" , 25000]
]

columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data2 , columns = columns)
df2

       Name  Age         City  Salary
0     Harsh   19      bhoopal   65000
1     sukhi   20  ashok nagar   68000
2  pratham    20    chindwara   64000
3   nishant   24        sagar   66000
4      ravi   25       bhopal   25000

In [5]:
# SELECTION AND INDEXING OF COLUMNS

df2 [["Name", "Age"]]

       Name  Age
0     Harsh   19
1     sukhi   20
2  pratham    20
3   nishant   24
4      ravi   25

In [6]:
# CREATING A NEW COLUMN 


df2["designation"] = ["AI/ML" , "CY" , "Full stack/DEV" , "Backend dev" , "Frontend dev"]
df2

       Name  Age         City  Salary     designation
0     Harsh   19      bhoopal   65000           AI/ML
1     sukhi   20  ashok nagar   68000              CY
2  pratham    20    chindwara   64000  Full stack/DEV
3   nishant   24        sagar   66000     Backend dev
4      ravi   25       bhopal   25000    Frontend dev

In [7]:
# REMOVING A COLUMN 

df2.drop("designation" , axis= 1)  # aagr inplace = true kiya toh designation permanent remove ho jayega

       Name  Age         City  Salary
0     Harsh   19      bhoopal   65000
1     sukhi   20  ashok nagar   68000
2  pratham    20    chindwara   64000
3   nishant   24        sagar   66000
4      ravi   25       bhopal   25000

In [8]:
# SELECTING ROWS 

df2.loc[1]
df2

       Name  Age         City  Salary     designation
0     Harsh   19      bhoopal   65000           AI/ML
1     sukhi   20  ashok nagar   68000              CY
2  pratham    20    chindwara   64000  Full stack/DEV
3   nishant   24        sagar   66000     Backend dev
4      ravi   25       bhopal   25000    Frontend dev

In [9]:
# SELECTING SUBSET OF ROWS AND COLUMNS 

df2.loc[[0, 1]][["City","Salary"]]
df2.loc[[2, 3]][["Name", "Age"]]

       Name  Age
2  pratham    20
3   nishant   24

In [10]:
# I ONLY WANT TO SEE THOSE PEOPLE WHOSE AGE IS ABOVE 20

df2[df2["Age"] > 20]

      Name  Age    City  Salary   designation
3  nishant   24   sagar   66000   Backend dev
4     ravi   25  bhopal   25000  Frontend dev

In [11]:
#  I ONLY WANT TO SEE THOSE PEOPLE WHOSE AGE IS ABOVE 20 AND THIER CITY MUST BE SAGAR

df2[(df2["Age"] > 20 ) & (df2["City"] == "sagar")]

      Name  Age   City  Salary  designation
3  nishant   24  sagar   66000  Backend dev

In [12]:
# FINDING MISSING DATA 

data3  = {
    "A" : [1, 2, np.nan, 4, 5],
    "B" : [np.nan , 2, 3, 4, 5],
    "C" : [1, 2, 3 , np.nan , np.nan],
    "D" : [1, np.nan,np.nan,np.nan, 5]
}

df3 = pd.DataFrame(data3)
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [13]:
df3.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [14]:
df3.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [15]:
df3.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [16]:
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [17]:
df3.dropna(thresh= 2)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [18]:
# FILLING THE MISSING DATA 

df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [19]:
df3.fillna(0) # jha jha null values h wah 0 store ho jayega

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [20]:
# FILLING VALUES IN PLACE OF NULL VALUES 

values = {"A" :0 , "B" :100 , "C" : 300, "D" :400}
df3.fillna (value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [21]:
# MERGING JOINING AND CONCATINATION 

# MERGING 2 DATA FRAMES 

employess = pd.DataFrame({
    "employe_id" : [1, 2, 3, 4, 5],
    "Name" : ["Harsh" , "Pratham" , "Ravi" , "Jat" , "Sukhi"],
    "Department" : ["HR" , "FINANCE" , "HOUSE KEEPER" , "FINANCE" , "HR"]
})

salaries = pd.DataFrame({
    "employe_id" : [1, 2, 3, 6, 7],
    "Salary" :[80000, 60000, 20000, 50000, 70000],
    "Bonous" :[6000, 3000, 2500, 2800 , 6000]
})

employess

   employe_id     Name    Department
0           1    Harsh            HR
1           2  Pratham       FINANCE
2           3     Ravi  HOUSE KEEPER
3           4      Jat       FINANCE
4           5    Sukhi            HR

In [22]:
salaries

   employe_id  Salary  Bonous
0           1   80000    6000
1           2   60000    3000
2           3   20000    2500
3           6   50000    2800
4           7   70000    6000

In [23]:
pd.merge(employess , salaries , on="employe_id" , how="inner")

   employe_id     Name    Department  Salary  Bonous
0           1    Harsh            HR   80000    6000
1           2  Pratham       FINANCE   60000    3000
2           3     Ravi  HOUSE KEEPER   20000    2500

In [24]:
pd.merge(employess , salaries , on="employe_id" , how="outer")

   employe_id     Name    Department   Salary  Bonous
0           1    Harsh            HR  80000.0  6000.0
1           2  Pratham       FINANCE  60000.0  3000.0
2           3     Ravi  HOUSE KEEPER  20000.0  2500.0
3           4      Jat       FINANCE      NaN     NaN
4           5    Sukhi            HR      NaN     NaN
5           6      NaN           NaN  50000.0  2800.0
6           7      NaN           NaN  70000.0  6000.0

In [25]:
pd.merge(employess , salaries , on="employe_id" , how="left")

   employe_id     Name    Department   Salary  Bonous
0           1    Harsh            HR  80000.0  6000.0
1           2  Pratham       FINANCE  60000.0  3000.0
2           3     Ravi  HOUSE KEEPER  20000.0  2500.0
3           4      Jat       FINANCE      NaN     NaN
4           5    Sukhi            HR      NaN     NaN

In [26]:
pd.merge(employess , salaries , on="employe_id" , how="right")

   employe_id     Name    Department  Salary  Bonous
0           1    Harsh            HR   80000    6000
1           2  Pratham       FINANCE   60000    3000
2           3     Ravi  HOUSE KEEPER   20000    2500
3           6      NaN           NaN   50000    2800
4           7      NaN           NaN   70000    6000

In [27]:
# CONCATINATION OF 2 DATA FRAMES 

conc1 = pd.DataFrame({
    "A":["A0" , "A1" , "A2"],
    "B":["B0" , "B1" , "B2"],
    "C":["C0" , "C1" , "C2"]
})

conc2 = pd.DataFrame ({
    "A":["A3" , "A4" , "A5"],
    "B":["B3" , "B4" , "B5"],
    "C":["C3" , "C4" , "C5"]
})
conc1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [28]:

pd.concat([conc1 , conc2])  # This is column wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [29]:
pd.concat([conc1 , conc2] , axis= 1) # This isi row wise

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [30]:
# JOINING 2 DATA FRAMES 

join1 = pd.DataFrame({
    "Name":  ["Harsh" , "sukhi" , "Pratham"]
}, index=[1, 2, 3])


join2 = pd.DataFrame({
    "Score" :[85, 90, 75]
    }, index=[2, 3, 4])

join2

   Score
2     85
3     90
4     75

In [31]:
join1.join(join2)

      Name  Score
1    Harsh    NaN
2    sukhi   85.0
3  Pratham   90.0

In [32]:
join1.join(join2 , how="outer")

      Name  Score
1    Harsh    NaN
2    sukhi   85.0
3  Pratham   90.0
4      NaN   75.0

In [33]:
# Group by Aggregation 
read = {
    "category" :["A" , "B" ,"A" , "B" ,"A" , "B" ,"A" , "B" ],
    "store" :["S1" , "S1" ,"S2" , "S2", "S1" , "S2" ,"S2" , "S1"  ],
    "sales" :[100, 200, 150, 250, 120, 180, 200, 300],
    "quantity" :[10, 15, 12, 18, 8, 20, 15, 25 ],
    "Date" : pd.date_range("2023-01-01", periods=8),
}
r1 = pd.DataFrame(read)
r1

  category store  sales  quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [34]:
# Group by category and calculate the sum of sales 

cat = r1.groupby("category")["sales"].sum()
cat

category
A    570
B    930
Name: sales, dtype: int64

In [35]:
# Group by store and calculate the sum of sales 

store = r1.groupby("store")["sales"].sum()
store

store
S1    720
S2    780
Name: sales, dtype: int64

In [36]:
# Group by multiple columns 

cat = r1.groupby(["category" , "store"])["sales"].sum()
cat

category  store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: sales, dtype: int64

In [37]:
# AGGEREGATION 

r1["sales"].mean()

# Aise hi median ,  std , variance , min , max, count ,  nikal skte h kisi bhi column ka

np.float64(187.5)

In [38]:
# shortcut for all operations 
r1["sales"].agg(["mean" , "median" , "sum" , "min" , "max" , "count" , "std"])

# mode print nhii kar skte h

mean       187.500000
median     190.000000
sum       1500.000000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
Name: sales, dtype: float64

In [39]:
# PIVOT TABLES 

tables = {
    "date" :pd.date_range("2023-01-01" , periods= 20),
    "product" :["A" , "B" , "C" , "D"] * 5,
    "region" :["east" , "west" , "north" , "sourth", "east" , "west" , "north" , "sourth", "east" , "west" ,
                "north" , "sourth", "east" , "west" , "north" , "sourth", "east" , "west" , "north" , "sourth"],

    "sales" :np.random.randint(100, 1000, 20),
    "units" :np.random.randint(10, 100, 20),
    "rep" :["john" , "mary" ,"bob" , "alice","john" , "mary" ,"bob" , "alice", "john" , "mary" 
            ,"bob" , "alice", "john" , "mary" ,"bob" , "alice", "john" , "mary" ,"bob" , "alice"]

}
t1 = pd.DataFrame(tables)

t1["Month"] = t1["date"].dt.month_name()
t1["Quarter"] = "Q" + t1["date"].dt.quarter.astype(str)

t1

         date product  region  sales  units    rep    Month Quarter
0  2023-01-01       A    east    930     63   john  January      Q1
1  2023-01-02       B    west    305     38   mary  January      Q1
2  2023-01-03       C   north    867     41    bob  January      Q1
3  2023-01-04       D  sourth    158     23  alice  January      Q1
4  2023-01-05       A    east    436     55   john  January      Q1
5  2023-01-06       B    west    732     38   mary  January      Q1
6  2023-01-07       C   north    240     73    bob  January      Q1
7  2023-01-08       D  sourth    932     54  alice  January      Q1
8  2023-01-09       A    east    810     85   john  January      Q1
9  2023-01-10       B    west    447     54   mary  January      Q1
10 2023-01-11       C   north    792     69    bob  January      Q1
11 2023-01-12       D  sourth    172     89  alice  January      Q1
12 2023-01-13       A    east    561     84   john  January      Q1
13 2023-01-14       B    west    905     93   mary  January      Q1
14 2023-01-15       C   north    321     20    bob  January      Q1
15 2023-01-16       D  sourth    992     15  alice  January      Q1
16 2023-01-17       A    east    268     31   john  January      Q1
17 2023-01-18       B    west    506     65   mary  January      Q1
18 2023-01-19       C   north    948     48    bob  January      Q1
19 2023-01-20       D  sourth    496     46  alice  January      Q1

In [40]:
pd.pivot_table(t1, values="sales" , index="region" , columns= "product" , aggfunc="median")

product      A      B      C      D
region
east     561.0    NaN    NaN    NaN
north      NaN    NaN  792.0    NaN
sourth     NaN    NaN    NaN  496.0
west       NaN  506.0    NaN    NaN

In [41]:
pivot2 = pd.pivot_table(t1, values=["sales" ,"units"] ,index="region" , columns= "product" )
pivot2

         sales                      units
product      A      B      C      D     A     B     C     D
region
east     601.0    NaN    NaN    NaN  63.6   NaN   NaN   NaN
north      NaN    NaN  633.6    NaN   NaN   NaN  50.2   NaN
sourth     NaN    NaN    NaN  550.0   NaN   NaN   NaN  45.4
west       NaN  579.0    NaN    NaN   NaN  57.6   NaN   NaN

In [42]:
# Cross Tabs 

pd.crosstab(t1 ["region"], t1 ["product"])

# yeh jo 5 aa rha h yeh no of counts h

product  A  B  C  D
region
east     5  0  0  0
north    0  0  5  0
sourth   0  0  0  5
west     0  5  0  0

In [43]:
# OPERATIONS 

ope = pd.DataFrame({
    "A" :[1, 2, 3, 4, 5],
    "B" :[10, 20, 30, 40, 50],
    "C" : [100, 200, 300, 400, 500]
})

ope

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [44]:
ope.shape

(5, 3)

In [45]:
ope.columns

Index(['A', 'B', 'C'], dtype='str')

In [46]:
ope.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [47]:
ope.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [48]:
# Broadcasting 

ope["A"]+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [49]:
# D.F Applying Function 


ope["D"] = ope["B"].apply(lambda x :x**2 )
ope

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500