In [82]:
import numpy as np 
import pandas as pd

In [83]:
df = pd.read_csv(r"Anime.csv")
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: Brotherhood (10 eps) Feb ...   9.10
1      2                      Steins;Gate (13 eps) Jan 2011   9.07
2      3        Bleach: Sennen Kessen-hen (18 eps) Sep 2023   9.06
3      4                         Gintama° (16 eps) Nov 2017   9.06
4      5  Shingeki no Kyojin Season 3 Part 2 (18 eps) No...   9.05
5      6                         Gintama' (13 eps) Mar 2022   9.04
6      7               Gintama: The Final (17 eps) Mar 2021   9.04
7      8           Hunter x Hunter (2011) (17 eps) Jun 2011   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra Romantic (10...   9.04
9     10                         Gintama' (10 eps) Mar 2012   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12             Ginga Eiyuu Densetsu (18 eps) Jul 2013   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tan (18...   8.99
13    14         Fruits Basket: The Final (17 eps) May 2013   8.99
14    15                         Gintama. (20 eps) May 2020   8.98
15    16                    Steins;Gate 0 (13 eps) Aug 2017   8.97
16    17  Shingeki no Kyojin: The Final Season (11 eps) ...   8.96
17    18                          Monster (10 eps) Mar 2021   8.95
18    19                     Cowboy Bebop (17 eps) May 2017   8.94
19    20                   Hajime no Ippo (10 eps) Oct 2020   8.93
20    21  Code Geass: Hangyaku no Lelouch R2 (17 eps) Ma...   8.92
21    22                     Vinland Saga (15 eps) Jun 2014   8.91
22    23                    Made in Abyss (18 eps) Feb 2011   8.90
23    24                         Mushishi (20 eps) Dec 2024   8.89
24    25             Clannad: After Story (12 eps) May 2015   8.88
25    26                Violet Evergarden (13 eps) Oct 2013   8.87
26    27                Mob Psycho 100 II (11 eps) Mar 2013   8.86
27    28       Owarimonogatari 2nd Season (18 eps) Apr 2015   8.85
28    29            Great Teacher Onizuka (15 eps) Aug 2024   8.84
29    30  March comes in like a lion 2nd Season (10 eps)...   8.83
30    31          Haikyuu!! Second Season (14 eps) Feb 2018   8.82
31    32  Haikyuu!! Karasuno Koukou VS Shiratorizawa Gak...   8.81
32    33    Mushishi Zoku Shou 2nd Season (10 eps) Apr 2019   8.80
33    34  Monogatari Series: Second Season (12 eps) May ...   8.79
34    35          Ping Pong the Animation (19 eps) Jul 2023   8.78
35    36                  Ashita no Joe 2 (15 eps) Jul 2013   8.77
36    37               Natsume Yuujinchou (16 eps) Nov 2014   8.76
37    38                   Kimi no Na wa. (13 eps) Mar 2024   8.75
38    39    Suzumiya Haruhi no Shoushitsu (15 eps) Aug 2020   8.74
39    40             Howl's Moving Castle (17 eps) Oct 2020   8.73
40    41    Sen to Chihiro no Kamikakushi (13 eps) Oct 2011   8.72
41    42                Princess Mononoke (19 eps) Dec 2018   8.71
42    43  Cowboy Bebop: Tengoku no Tobira (11 eps) Apr 2012   8.70
43    44  Evangelion: 3.0+1.0 Thrice Upon a Time (13 eps...   8.69
44    45          Violet Evergarden Movie (16 eps) Oct 2012   8.68
45    46                    Wolf Children (20 eps) Dec 2012   8.67
46    47                      Summer Wars (16 eps) May 2023   8.66
47    48                 Tokyo Godfathers (13 eps) Jul 2018   8.65
48    49                     Perfect Blue (13 eps) May 2024   8.64
49    50                          Paprika (20 eps) Oct 2017   8.63

In [84]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: Brotherhood (10 eps) Feb ...   9.10
1     2                      Steins;Gate (13 eps) Jan 2011   9.07
2     3        Bleach: Sennen Kessen-hen (18 eps) Sep 2023   9.06
3     4                         Gintama° (16 eps) Nov 2017   9.06
4     5  Shingeki no Kyojin Season 3 Part 2 (18 eps) No...   9.05

In [85]:
df.loc[3]["Title"]

'Gintama° (16 eps) Nov 2017'

In [86]:
# Ques1 = Make a new column for Episodes count 


def extract_episodes(txt):
    start = txt.find("(", txt.rfind("("))
    end = txt.find(")", start)

    if start != -1 and end != -1:
        content = txt[start+1:end]

        if "eps" in content:
            return int(content.split()[0])

    return None
df["Episodes"] = df["Title"].apply(extract_episodes)
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: Brotherhood (10 eps) Feb ...   9.10        10
1      2                      Steins;Gate (13 eps) Jan 2011   9.07        13
2      3        Bleach: Sennen Kessen-hen (18 eps) Sep 2023   9.06        18
3      4                         Gintama° (16 eps) Nov 2017   9.06        16
4      5  Shingeki no Kyojin Season 3 Part 2 (18 eps) No...   9.05        18
5      6                         Gintama' (13 eps) Mar 2022   9.04        13
6      7               Gintama: The Final (17 eps) Mar 2021   9.04        17
7      8           Hunter x Hunter (2011) (17 eps) Jun 2011   9.04        17
8      9  Kaguya-sama wa Kokurasetai: Ultra Romantic (10...   9.04        10
9     10                         Gintama' (10 eps) Mar 2012   9.03        10
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        14
11    12             Ginga Eiyuu Densetsu (18 eps) Jul 2013   9.02        18
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tan (18...   8.99        18
13    14         Fruits Basket: The Final (17 eps) May 2013   8.99        17
14    15                         Gintama. (20 eps) May 2020   8.98        20
15    16                    Steins;Gate 0 (13 eps) Aug 2017   8.97        13
16    17  Shingeki no Kyojin: The Final Season (11 eps) ...   8.96        11
17    18                          Monster (10 eps) Mar 2021   8.95        10
18    19                     Cowboy Bebop (17 eps) May 2017   8.94        17
19    20                   Hajime no Ippo (10 eps) Oct 2020   8.93        10
20    21  Code Geass: Hangyaku no Lelouch R2 (17 eps) Ma...   8.92        17
21    22                     Vinland Saga (15 eps) Jun 2014   8.91        15
22    23                    Made in Abyss (18 eps) Feb 2011   8.90        18
23    24                         Mushishi (20 eps) Dec 2024   8.89        20
24    25             Clannad: After Story (12 eps) May 2015   8.88        12
25    26                Violet Evergarden (13 eps) Oct 2013   8.87        13
26    27                Mob Psycho 100 II (11 eps) Mar 2013   8.86        11
27    28       Owarimonogatari 2nd Season (18 eps) Apr 2015   8.85        18
28    29            Great Teacher Onizuka (15 eps) Aug 2024   8.84        15
29    30  March comes in like a lion 2nd Season (10 eps)...   8.83        10
30    31          Haikyuu!! Second Season (14 eps) Feb 2018   8.82        14
31    32  Haikyuu!! Karasuno Koukou VS Shiratorizawa Gak...   8.81        17
32    33    Mushishi Zoku Shou 2nd Season (10 eps) Apr 2019   8.80        10
33    34  Monogatari Series: Second Season (12 eps) May ...   8.79        12
34    35          Ping Pong the Animation (19 eps) Jul 2023   8.78        19
35    36                  Ashita no Joe 2 (15 eps) Jul 2013   8.77        15
36    37               Natsume Yuujinchou (16 eps) Nov 2014   8.76        16
37    38                   Kimi no Na wa. (13 eps) Mar 2024   8.75        13
38    39    Suzumiya Haruhi no Shoushitsu (15 eps) Aug 2020   8.74        15
39    40             Howl's Moving Castle (17 eps) Oct 2020   8.73        17
40    41    Sen to Chihiro no Kamikakushi (13 eps) Oct 2011   8.72        13
41    42                Princess Mononoke (19 eps) Dec 2018   8.71        19
42    43  Cowboy Bebop: Tengoku no Tobira (11 eps) Apr 2012   8.70        11
43    44  Evangelion: 3.0+1.0 Thrice Upon a Time (13 eps...   8.69        13
44    45          Violet Evergarden Movie (16 eps) Oct 2012   8.68        16
45    46                    Wolf Children (20 eps) Dec 2012   8.67        20
46    47                      Summer Wars (16 eps) May 2023   8.66        16
47    48                 Tokyo Godfathers (13 eps) Jul 2018   8.65        13
48    49                     Perfect Blue (13 eps) May 2024   8.64        13
49    50                          Paprika (20 eps) Oct 2017   8.63        20

In [87]:
# type conversion 

df["Episodes"].astype(int)

0     10
1     13
2     18
3     16
4     18
5     13
6     17
7     17
8     10
9     10
10    14
11    18
12    18
13    17
14    20
15    13
16    11
17    10
18    17
19    10
20    17
21    15
22    18
23    20
24    12
25    13
26    11
27    18
28    15
29    10
30    14
31    17
32    10
33    12
34    19
35    15
36    16
37    13
38    15
39    17
40    13
41    19
42    11
43    13
44    16
45    20
46    16
47    13
48    13
49    20
Name: Episodes, dtype: int64

In [88]:
#  Que2 = Make a new column for time stamps 

def extraction_time(txt):
    data = ""

    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i + 2, min(i + 10, len(txt))):
                data += txt[j]

            return data.strip()

    return None

In [89]:
df["Total time "] = df["Title"].apply(extraction_time)
df

,Rank,Title,Score,Episodes,Total time
0,1,Fullmetal Alchemist: Brotherhood (10 eps) Feb ...,9.10,10,Feb 2013
1,2,Steins;Gate (13 eps) Jan 2011,9.07,13,Jan 2011
2,3,Bleach: Sennen Kessen-hen (18 eps) Sep 2023,9.06,18,Sep 2023
3,4,Gintama° (16 eps) Nov 2017,9.06,16,Nov 2017
4,5,Shingeki no Kyojin Season 3 Part 2 (18 eps) No...,9.05,18,Nov 2016
5,6,Gintama' (13 eps) Mar 2022,9.04,13,Mar 2022
6,7,Gintama: The Final (17 eps) Mar 2021,9.04,17,Mar 2021
7,8,Hunter x Hunter (2011) (17 eps) Jun 2011,9.04,17,(17 eps)
8,9,Kaguya-sama wa Kokurasetai: Ultra Romantic (10...,9.04,10,Apr 2020
9,10,Gintama' (10 eps) Mar 2012,9.03,10,Mar 2012
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,14,Feb 2023
11,12,Ginga Eiyuu Densetsu (18 eps) Jul 2013,9.02,18,Jul 2013
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tan (18...,8.99,18,Feb 2014
13,14,Fruits Basket: The Final (17 eps) May 2013,8.99,17,May 2013
14,15,Gintama. (20 eps) May 2020,8.98,20,May 2020
15,16,Steins;Gate 0 (13 eps) Aug 2017,8.97,13,Aug 2017
16,17,Shingeki no Kyojin: The Final Season (11 eps) ...,8.96,11,Sep 2022
17,18,Monster (10 eps) Mar 2021,8.95,10,Mar 2021
18,19,Cowboy Bebop (17 eps) May 2017,8.94,17,May 2017
19,20,Hajime no Ippo (10 eps) Oct 2020,8.93,10,Oct 2020
20,21,Code Geass: Hangyaku no Lelouch R2 (17 eps) Ma...,8.92,17,Mar 2023
21,22,Vinland Saga (15 eps) Jun 2014,8.91,15,Jun 2014
22,23,Made in Abyss (18 eps) Feb 2011,8.90,18,Feb 2011
23,24,Mushishi (20 eps) Dec 2024,8.89,20,Dec 2024
24,25,Clannad: After Story (12 eps) May 2015,8.88,12,May 2015
25,26,Violet Evergarden (13 eps) Oct 2013,8.87,13,Oct 2013
26,27,Mob Psycho 100 II (11 eps) Mar 2013,8.86,11,Mar 2013
27,28,Owarimonogatari 2nd Season (18 eps) Apr 2015,8.85,18,Apr 2015
28,29,Great Teacher Onizuka (15 eps) Aug 2024,8.84,15,Aug 2024
29,30,March comes in like a lion 2nd Season (10 eps)...,8.83,10,Jan 2024
30,31,Haikyuu!! Second Season (14 eps) Feb 2018,8.82,14,Feb 2018
31,32,Haikyuu!! Karasuno Koukou VS Shiratorizawa Gak...,8.81,17,Jan 2016
32,33,Mushishi Zoku Shou 2nd Season (10 eps) Apr 2019,8.80,10,Apr 2019
33,34,Monogatari Series: Second Season (12 eps) May ...,8.79,12,May 2020
34,35,Ping Pong the Animation (19 eps) Jul 2023,8.78,19,Jul 2023
35,36,Ashita no Joe 2 (15 eps) Jul 2013,8.77,15,Jul 2013
36,37,Natsume Yuujinchou (16 eps) Nov 2014,8.76,16,Nov 2014
37,38,Kimi no Na wa. (13 eps) Mar 2024,8.75,13,Mar 2024
38,39,Suzumiya Haruhi no Shoushitsu (15 eps) Aug 2020,8.74,15,Aug 2020
39,40,Howl's Moving Castle (17 eps) Oct 2020,8.73,17,Oct 2020
40,41,Sen to Chihiro no Kamikakushi (13 eps) Oct 2011,8.72,13,Oct 2011
41,42,Princess Mononoke (19 eps) Dec 2018,8.71,19,Dec 2018
42,43,Cowboy Bebop: Tengoku no Tobira (11 eps) Apr 2012,8.70,11,Apr 2012
43,44,Evangelion: 3.0+1.0 Thrice Upon a Time (13 eps...,8.69,13,Feb 2013
44,45,Violet Evergarden Movie (16 eps) Oct 2012,8.68,16,Oct 2012
45,46,Wolf Children (20 eps) Dec 2012,8.67,20,Dec 2012
46,47,Summer Wars (16 eps) May 2023,8.66,16,May 2023
47,48,Tokyo Godfathers (13 eps) Jul 2018,8.65,13,Jul 2018
48,49,Perfect Blue (13 eps) May 2024,8.64,13,May 2024
49,50,Paprika (20 eps) Oct 2017,8.63,20,Oct 2017

In [90]:
# Que3 = which anime has the hieghest score 

df[df["Score"] == df["Score"].max()]["Title"]

0    Fullmetal Alchemist: Brotherhood (10 eps) Feb ...
Name: Title, dtype: str

In [91]:
# Que4 = give me top 5 heighest scoring anime 

df["Title"].head()

0    Fullmetal Alchemist: Brotherhood (10 eps) Feb ...
1                        Steins;Gate (13 eps) Jan 2011
2          Bleach: Sennen Kessen-hen (18 eps) Sep 2023
3                           Gintama° (16 eps) Nov 2017
4    Shingeki no Kyojin Season 3 Part 2 (18 eps) No...
Name: Title, dtype: str

In [92]:
# Ques5 = which anime has the heighest episodes count 

df[df["Episodes"] == df["Episodes"].max()]

    Rank                            Title  Score  Episodes Total time
14    15       Gintama. (20 eps) May 2020   8.98        20    May 2020
23    24       Mushishi (20 eps) Dec 2024   8.89        20    Dec 2024
45    46  Wolf Children (20 eps) Dec 2012   8.67        20    Dec 2012
49    50        Paprika (20 eps) Oct 2017   8.63        20    Oct 2017